[[section-introduction-and-goals]]
=	Einführung und Ziele

Die Idee hinter dem TI-Messenger: ein sicheres Übermittlungsverfahren zu schaffen, mit dem Kurznachrichten über Apps ortsunabhängig auf dem Smartphone und Tablet oder stationär auf dem PC ausgetauscht werden können – digitale Kommunikation in Echtzeit. „Wir konzipieren den TI-Messenger in der ersten Ausbaustufe für Beschäftigte im Gesundheitswesen, die unkompliziert mit Kolleginnen und Kollegen zu medizinisch relevanten Themen kommunizieren möchten. Der Bedarf nach einer schnellen und sicheren Kommunikation ist groß“, erklärt Eric Grey, Produktmanager für den TI-Messenger bei der gematik.

Der Versand von Kurznachrichten in Praxen hat in den vergangenen Jahren deutlich zugenommen, nicht zuletzt hat die Corona-Pandemie zu einem Digitalisierungsschub geführt. Der TI-Messenger soll KIM (Kommunikation im Medizinwesen) ergänzen. KIM sorgt bereits jetzt für den sicheren E-Mail-Austausch sensibler Informationen wie Befunde, Bescheide, Abrechnungen und Röntgenbilder über die Telematikinfrastruktur und ersetzt damit z.B. den ausgedruckten Arztbrief. Der TI-Messenger ist dagegen auf die schnelle und asynchrone Ad-hoc-Kommunikation mit Kurznachrichten ausgelegt.


== Aufgabenstellung

Mit den TI-Messenger-Standards geht die gematik neue Wege und möchte durch die Verwendung eines bestehenden Open-Source-Protokolls den Ansprüchen an Interoperabilität, Integrierbarkeit und Innovationsoffenheit gerecht werden. Zentrale Aspekte sind Marktoffenheit für Anbieter, Wahlfreiheit für Nutzer sowie schnelle Verfügbarkeit der Lösung.

 

Industriepartner und Dritte können auf Basis der Festlegungen eigene Messenger-Lösungen nutzerzentriert entwickeln und ihren Kunden diese nach Zulassung durch die gematik anbieten. Nutzer können entscheiden, über welchen TI-Messenger sie kommunizieren möchten. Wesentliche Unterschiede zu bereits bestehenden Messengerlösungen sind die Erreichbarkeit aller TI-Messenger-Nutzer durch die Gewährleistung von Interoperabilität zwischen einzelnen Messenger-Diensten und die Bereitstellung eines zentralen Adressbuches aller authentifizierten Nutzer. Dies sind Alleinstellungsmerkmale des gematik-Standards und ein Meilenstein für die sektorenübergreifende Kommunikation im Gesundheitswesen. Bereits im Frühjahr 2022 kann mit ersten Lösungen am Markt gerechnet werden.

== Qualitätsziele

[NOTE]
====
.Inhalt
Die Top-3 bis Top-5 der Qualitätsziele für die Architektur, deren Erfüllung oder Einhaltung den maßgeblichen Stakeholdern besonders wichtig sind.
Gemeint sind hier wirklich Qualitätsziele, die nicht unbedingt mit den Zielen des Projekts übereinstimmen. Beachten Sie den Unterschied.

.Motivation
Weil Qualitätsziele grundlegende Architekturentscheidungen oft maßgeblich beeinflussen, sollten Sie die für Ihre Stakeholder relevanten Qualitätsziele kennen, möglichst konkret und operationalisierbar.

.Form
Tabellarische Darstellung der Qualitätsziele mit möglichst konkreten Szenarien, geordnet nach Prioritäten.
====

== Stakeholder

[NOTE]
====
.Inhalt
Expliziter Überblick über die Stakeholder des Systems – über alle Personen, Rollen oder Organisationen –, die

* die Architektur kennen sollten oder
* von der Architektur überzeugt werden müssen,
* mit der Architektur oder dem Code arbeiten (z.B. Schnittstellen nutzen),
* die Dokumentation der Architektur für ihre eigene Arbeit benötigen,
* Entscheidungen über das System und dessen Entwicklung treffen.

.Motivation
Sie sollten die Projektbeteiligten und -betroffenen kennen, sonst erleben Sie später im Entwicklungsprozess Überraschungen.
Diese Stakeholder bestimmen unter anderem Umfang und Detaillierungsgrad der von Ihnen zu leistenden Arbeit und Ergebnisse.

.Form
Tabelle mit Rollen- oder Personennamen, sowie deren Erwartungshaltung bezüglich der Architektur und deren Dokumentation.
====

[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| _<Rolle-1>_ | _<Kontakt-1>_ | _<Erwartung-1>_
| _<Rolle-2>_ | _<Kontakt-2>_ | _<Erwartung-2>_ 
|===
