= Was kann Asciidoc so alles?

[TIP]
====
Für ausführlichen Syntax schaut bitte https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[die offizielle Quick Reference] an.
====

== PlantUML Diagramme

[plantuml, svg]     
....
skinparam monochrome true

participant participant as Foo
actor       actor       as Foo1
boundary    boundary    as Foo2
control     control     as Foo3
entity      entity      as Foo4
database    database    as Foo5
collections collections as Foo6
queue       queue       as Foo7
Foo -> Foo1 : To actor 
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7: To queue
....

.PlantUML Quellcode
[source,plantuml]
----
skinparam monochrome true

participant participant as Foo
actor       actor       as Foo1
boundary    boundary    as Foo2
control     control     as Foo3
entity      entity      as Foo4
database    database    as Foo5
collections collections as Foo6
queue       queue       as Foo7
Foo -> Foo1 : To actor 
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7: To queue
----

== Source Code Syntax Highlighting

Asciidoc und Antora unterstützen Syntax-Highlight für viele Programmiersprachen und andere strukturierte Formate. https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md[Hier ist die komplette liste].

[CAUTION]
====
Antora unterstützt nur HighlightJS als Code-Formatter. Auch die Auswahl von einzelnen Zeilen und Zeilennummer werden nicht unterstützt. Großer Minuspunkt hier.
====

.Kotrlin
[source,kotlin]
----
// Hello World Program

fun main(args : Array<String>) {
    println("Hello, World!")
}
----

.Swift
[source,swift]
----
let cancellable = publisher.sink(
    receiveCompletion: { completion in
        // Called once, when the publisher was completed.
        print(completion)
    },
    receiveValue: { value in
        // Can be called multiple times, each time that a
        // new value was emitted by the publisher.
        print(value)
    }
)
----